# Generated by Django 5.2.7 on 2025-11-26 21:46

from django.db import migrations, models
from recipes.models.recipes import Tag

def create_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    default_tags = [
        "Vegetarian",
        "Vegan",
        "Dairy-Free",
        "Gluten-Free",
        "High Protein",
        "Halal",
        "Nut-Free",
    ]

    for name in default_tags:
        Tag.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_alter_recipe_publication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recipes.tag'),
        ),
        migrations.RunPython(create_tags),
    ]
