# Generated by Django 5.2.7 on 2025-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients, one per line in the format: name quantity measurement'),
        ),
    ]
