# Generated by Django 5.2.7 on 2025-11-26 22:46

from django.db import migrations

def create_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    default_tags = [
        "Vegetarian",
        "Vegan",
        "Dairy-Free",
        "Gluten-Free",
        "High Protein",
        "Halal",
        "Nut-Free",
    ]
    for name in default_tags:
        Tag.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_tag_recipe_tags'),
    ]

    operations = [
        migrations.RunPython(create_tags),
    ]
