# Generated by Django 5.2.7 on 2025-12-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_follow'),
        ('recipes', '0006_populate_tags'),
    ]

    operations = [
    ]
