# Generated by Django 5.2.7 on 2025-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_description_alter_recipe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('me', 'Only Me')], default='public', max_length=10),
        ),
    ]
